### ISSUE TITLE
aide 兼容性问题

### ISSUE THREAD

**Issue by Kazusa1412** [ToneCloud/AndroidSDK#1]
不支持 Lambda 表达式

**Comment by wwxiaoqi** [comment]
## 可尝试使用如下几种方法：

- 删除 Lambda 表达式
- 使用 Termux 进行构建

**Comment by Kazusa1412** [comment]
> ## 可尝试使用如下几种方法：
> * 删除 Lambda 表达式
> * 使用 Termux 进行构建

在 dev 分支中已替换 Lambda 表达式为匿名类
